language: scala
os:
  - linux
scala:
  - 2.11.7
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
script:
  - sbt test
  - sbt server/universal:packageBin

git:
  submodules: false

services:
  - elasticsearch

before_script:
  - 'gem install sass --version "=3.2.12"'
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start