language: scala
os:
  - linux
scala:
  - 2.11.7
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
script:
  - sbt test

git:
  submodules: false

before_script:
  - 'gem install sass --version "=3.2.12"'